# Estimation {#estimation}


## Reduce form VAR(p)


$$y_{t}= A_1y_{t-1} + \cdots + A_p y_{t-p} + u_t$$



## Structural Form VAR(p)


$$B_0y_{t}= B_{1}y_{{t-1}}+\cdots +B_{p}y_{{t-p}}+e_{t}$$

Let try some text here:

 - $E(e_t) = 0$ —  every error term has mean zero $\alpha$ 
 
 - $E (e_{t}e_{t}')= \Omega$ —  the contemporaneous covariance matrix of error terms is $\Omega$
 (a k × k positive-semidefinite matrix)
 
 - $E(e_{t}e_{{t-k}}')=0$ — for any non-zero k — there is no correlation across time; in particular, no serial correlation in individual error terms.[1]
 

$$y_{t}= \underbrace{B_0^{-1}B_{1}y_{{t-1}}}_{A_1} + \cdots + \underbrace{B_0^{-1}B_{p}y_{{t-p}}}_{A_p} + \underbrace{B_0^{-1}e_{t}}_{w_t}$$


## Compact Form 

Consider the VAR(p) model (??) written in more compact form

$$y_t = 

$$Y = AZ + U$$
where $Z = [1, y_{t-1}', \cdots, y_{t-p}']$


$$\hat{A} = [\hat{\nu_t}, \hat{A_1}, \cdots, \hat{A_p}] = (Z'Z)^{-1}Z'Y$$
$$\hat{U} = Y - Z\hat{A}$$
$$\hat{\Sigma_u} = \dfrac{(\hat{U}' \hat{U})^{-1}}{(N-Kp-p-1)}$$

### Impulse Response Function

Given $B_)$ and $u_t$, we immediately obtain $w_t = B_0u_t$. Having identified the
structural shocks $w_t$, our interest usually is not in the shocks themselves, how-
ever, but in the responses of each element of yt = (y1t,...,yKt) to a one-time
impulse in wt = (w1t,...,wKt)

$$\dfrac{∂yt+i}{∂w_t} = \Theta_i, \quad i = 0, 1, 2, . . . , H, $$

where Θi is a K ×K matrix. The elements of this matrix for given i are denoted as

$$ θ_{jk,i} = \dfrac{∂y_{j,t+i}}{∂w_{kt}} $$ 
such that $\Theta_i = [\theta_{jk,t}].$

By successive substitution for $Y_{t−i}$, equation can be written as
$$ Y_{t+i} = A_{i+1}Y_{t−1} + \sum^i_{j=0} A_jU_{t+i−j}$$

Left-multiplying this equation by $J ≡ [I_K, 0_{K×K(p−1)}]$ yields
\begin{align}
y_{t+i} = & JA_{i+1}Y_{t−1} + \sum^{i}_{j=0} JA^jU_{t+i−j} \\
        = & JA^{i+1}Y_{t−1} + \sum^i_{j=0} JA^{j}J'JU_{t+i−j} \\
        = & JA^{i+1}Y_{t−1} + \sum^i_{j=0} JA^{j}Ju_{t+i−j} \\
\end{align}

Thus, the response of the variable j = 1,...,K in the VAR(p) system to a unit
shock ukt, k = 1,...,K, i periods ago, is given by:

$$ \underset{K×K}{\Phi_i} = [\phi_{jk,i}] ≡ JA^iJ'$$

The $\phi_i$ are also sometimes referred to as responses to VAR forecast errors, as
dynamic multipliers, or simply as reduced-form impulse responses.

## Minessota prior

The simplest form of prior distributions for VAR models is known as the Minnesota (or Litterman) prior. In this framework, it is assumed that the VAR residual variance-covariance matrix $\Sigma$ is known. Hence, the only object left to estimate is the vector of parameters $\beta$. To obtain the posterior distribution for $\beta$ from 1.2.3, one needs two elements: the likelihood function $f(y |\beta)$ for the data,
and a prior distribution $\pi(\beta)$ for $\beta$.

$y\sim \mathcal{N}(\tilde{X}\beta, \tilde{\Sigma})$ Therefore, one may write the likelihood for y as:

$$f(y|\beta, \tilde{\Sigma}) = (2\pi)^{-nT/2} |\tilde{\Sigma}|^{-1/2}\exp[-\dfrac{1}{2}(y-\tilde{X}\beta)\tilde{\Sigma}^{-1}(y-\tilde{X}\beta)]$$

Ignoring terms independent from $\beta$ relegated to proportionality simplifies to:

$$f(y|\beta, \tilde{\Sigma})\propto \exp[-\dfrac{1}{2}(y-\tilde{X}\beta)\tilde{\Sigma}^{-1}(y-\tilde{X}\beta)]$$
 
 Now turn to the prior distribution for $\beta$. It is assumed that $\beta$ follows a multivariate normal distribution, with mean $\beta_0$ and covariance matrix $\Omega_0$:
 
 $$\pi(\beta) \sim \mathcal{N}(\beta_0, \Omega_0)$$
 
To identify $\beta_0$ and $\Omega_0$, Litterman (1986) proposed the following strategy. As most observed macroeconomic variables seem to be characterized by a unit root (in the sense that their changes are impossible to forecast), our prior belief should be that each endogenous variable included in the model presents a unit root in its first own lags, and coefficients equal to zero for further lags and cross-variable lag coefficients. In the absence of prior belief about exogenous variables, the most reasonable strategy is to assume that they are neutral with respect to the endogenous variables, and hence that their coefficients are equal to zero as well. These elements translate into $\beta_0$ being a vector of zeros, save for the entries concerning the first own lag of each endogenous variable which are attributed values of 1. Note though that in the case of variables known to be stationary, this unit root hypothesis may not be suitable, so that a value around 0.8 may be preferred to a value of 1.

