# Algorithms {#algo}

## IRF

### Companion

### Algorithm 1 {#irf_algo1}

1. Create a 2D-array of $Kp \times (h+1) \times Kp$
2. Assign the shock to the first observation (unit, se, etc)
3. Iterate over the horizons 1, 2, ..., h where
$$ irf_{i+1} = irf_{i} A'$$

### Algorithm 2 {#irf_algo2}

1. Create a array $J = [I_k, 0_{K\times K(p-1)}]$
2. Create an 3D-array of $Kp \times (h + 1) \times Kp$ to store the irfs
2. Assign the shock to the first observation (unit, se, etc)
3. Iterate over the horizons for i = 1,2, ..., h where
$$ irf_{i+1} = J A^i J'$$

## Error Bands for Impulse Response Function

### Asymptotic {#irf_as_algo1}

### Mote Carlo {#irf_mc_algo1}

### Bootstrap {#irf_boot_algo1}

### Bootstrap after Bootstrap {#irf_boot2_algo1}




Montecarlo method proceeds as follows.1. DrawˆπlfromN(ˆπ,ˆΩ⊗ˆQ−1).2. computeC(L)l.3. Repeat 1-2M(withMbig, i.e.1000) times.4. For all the elementsCi,j,h,i,j= 1,...,n,h= 1,2,...of the impulse responsefunctions  collect  theαth  and  1−αth  percentile  across  the`draws  as  aconfidence interval forCi,j,h.


### Algorithm 2.2.1 (impulse response functions, all priors):

1. Define the number of iterations (It − Bu) of the algorithm, and the time horizon h.
2. Fix i = 1. Then set yi,T = 1.
3. At iteration n, draw $\beta_{n}$ from its posterior distributions. Simply recycle draw n from the Gibbs sampler.
4. Generate recursively the simulated values $\tilde{y}^{(n)}_{T+1}$, $\tilde{y}^{(n)}_{T+2}$, $\ldots$, $\tilde{y}^{(n)}_{T+h}$ from 1.1.2: $\tilde{y}^{(n)}_{T+1} = A_1y_t + A_2y_{t-1} + \ldots + A_py_{T+1-p}$. Once ˜yT+1 is computed, use: ˜y
(n)
T+2 = A1˜y
(n)
T+1 + A2yT + ... + ApyT+2−p
And continue this way until ˜y
(n)
T+h is obtained. Once again, both the exogenous terms and the
shocks are ignored since they are assumed to take a value of 0 at all periods. The values of
A,
1,A,
2...A,
p come from $\beta_{n}$.
5. Discard $\beta_{n}$ to obtain draws ˜y
(n)
T+1, ˜y
(n)
T+2...˜y
(n)
T+h from the predictive distribution f(yT+1:T+h |yT ).
6. Repeat until (It−Bu) iterations have been performed. This produces:
n
˜y
(n)
T+1 |yT , ˜y
(n)
T+2 |yT , ..., ˜y
(n)
T+h |yT
oIt−j=a sample of independent draws from the joint predictive distribution in the case yi,T = 1.
7. Go back to step 2, and fix i = 2. Then go through steps 3-6 all over again. Then repeat the process for i = 3, ..., n. This generates the impulse response functions for all the shocks in the model.
